management:
  context-path: /devops
  
info:
  project:
    groupId: ${project.groupId}
    artifactId: ${project.artifactId}
    version: ${project.version}
  
server:
  context-path: /api/v${project.version.major}